name: CI/CD-nestJS

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", dev ]
    types: [ "opened", "reopened", "synchronize", "closed" ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [20.10.0]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{secrets.TOKEN}}
    
    - name: Set up NodeJS ${{matrix.node-version}} setting
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependency
      run: npm install 

    - name: Check Lint Code
      run: npm run lint 

    - name: Build with NPM
      run: npm run build

    - name: Test with NPM
      run: npm run test
      
  deploy-dev:
    if: github.ref == 'refs/heads/dev' && (github.event.pull_request.merged == true || github.event_name == 'push')
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{secrets.TOKEN}}

    - name: Docker build & push
      run: |
        echo '${{ secrets.DOCKER_PASSWORD}}' > docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_DEV_IMAGE }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_DEV_IMAGE }}

    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_HOST }}
        port: 22
        username: ${{ secrets.DEV_USERNAME }}
        key: ${{ secrets.DEV_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_DEV_IMAGE }}
          docker rm -f $(docker ps -qa)
          docker run -d -p 80:8082 -v $HOME/logs:/logs ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_DEV_IMAGE }}
          docker container prune -f
          docker image prune -f
